export interface CanonicalThemeSpec {
  id: string;
  label: string;
  detail: string;
  appearance: "light" | "dark";
  canvas: string;
  accent: string;
  surface?: string;
  category: "website" | "dark" | "light";
}

/**
 * The Liquid Glass theme reference directly from website/assets/css/site.css.
 * Dark editor-navy canvas (#0b0e14), well surfaces (#131823 / #1a2030), and electric blue accent (#4f9cff).
 */
export const LIQUID_GLASS_THEME_SPEC: CanonicalThemeSpec = {
  id: "liquid-glass",
  label: "Liquid Glass",
  detail: "Swarm Code website signature · Deep navy glass & electric blue",
  appearance: "dark",
  canvas: "#0b0e14",
  accent: "#4f9cff",
  surface: "#131823",
  category: "website",
};

/**
 * The 26 canonical themes from SwarmCode/UI/Theme/AppTheme.swift and website/assets/js/code.js.
 */
export const SWARM_CODE_CANONICAL_THEME_SPECS: ReadonlyArray<CanonicalThemeSpec> = [
  LIQUID_GLASS_THEME_SPEC,
  {
    id: "catppuccin-mocha",
    label: "Catppuccin Mocha",
    detail: "Dark · Mauve",
    appearance: "dark",
    canvas: "#1e1e2e",
    accent: "#cba6f7",
    category: "dark",
  },
  {
    id: "catppuccin-latte",
    label: "Catppuccin Latte",
    detail: "Light · Mauve",
    appearance: "light",
    canvas: "#eff1f5",
    accent: "#8839ef",
    category: "light",
  },
  {
    id: "dracula",
    label: "Dracula",
    detail: "Dark · Purple",
    appearance: "dark",
    canvas: "#282a36",
    accent: "#bd93f9",
    category: "dark",
  },
  {
    id: "tokyo-night",
    label: "Tokyo Night",
    detail: "Dark · Blue",
    appearance: "dark",
    canvas: "#1a1b26",
    accent: "#7aa2f7",
    category: "dark",
  },
  {
    id: "nord",
    label: "Nord",
    detail: "Dark · Frost",
    appearance: "dark",
    canvas: "#2e3440",
    accent: "#88c0d0",
    category: "dark",
  },
  {
    id: "gruvbox",
    label: "Gruvbox",
    detail: "Dark · Orange",
    appearance: "dark",
    canvas: "#282828",
    accent: "#fe8019",
    category: "dark",
  },
  {
    id: "gruvbox-light",
    label: "Gruvbox Light",
    detail: "Light · Rust",
    appearance: "light",
    canvas: "#fbf1c7",
    accent: "#af3a03",
    category: "light",
  },
  {
    id: "one-dark",
    label: "One Dark",
    detail: "Dark · Blue",
    appearance: "dark",
    canvas: "#282c34",
    accent: "#61afef",
    category: "dark",
  },
  {
    id: "everforest",
    label: "Everforest",
    detail: "Dark · Green",
    appearance: "dark",
    canvas: "#2d353b",
    accent: "#a7c080",
    category: "dark",
  },
  {
    id: "kanagawa",
    label: "Kanagawa",
    detail: "Dark · Wave blue",
    appearance: "dark",
    canvas: "#1f1f28",
    accent: "#7e9cd8",
    category: "dark",
  },
  {
    id: "rose-pine",
    label: "Rosé Pine",
    detail: "Dark · Rose",
    appearance: "dark",
    canvas: "#191724",
    accent: "#eb6f92",
    category: "dark",
  },
  {
    id: "solarized-dark",
    label: "Solarized Dark",
    detail: "Dark · Blue",
    appearance: "dark",
    canvas: "#002b36",
    accent: "#268bd2",
    category: "dark",
  },
  {
    id: "solarized-light",
    label: "Solarized Light",
    detail: "Light · Blue",
    appearance: "light",
    canvas: "#fdf6e3",
    accent: "#268bd2",
    category: "light",
  },
  {
    id: "github-dark",
    label: "GitHub Dark",
    detail: "Dark · Blue",
    appearance: "dark",
    canvas: "#0d1117",
    accent: "#4493f8",
    category: "dark",
  },
  {
    id: "github-light",
    label: "GitHub Light",
    detail: "Light · Blue",
    appearance: "light",
    canvas: "#ffffff",
    accent: "#0969da",
    category: "light",
  },
  {
    id: "ayu",
    label: "Ayu",
    detail: "Dark · Amber",
    appearance: "dark",
    canvas: "#0f1419",
    accent: "#e6b450",
    category: "dark",
  },
  {
    id: "night-owl",
    label: "Night Owl",
    detail: "Dark · Blue",
    appearance: "dark",
    canvas: "#011627",
    accent: "#82aaff",
    category: "dark",
  },
  {
    id: "monokai",
    label: "Monokai",
    detail: "Dark · Pink",
    appearance: "dark",
    canvas: "#272822",
    accent: "#f92672",
    category: "dark",
  },
  {
    id: "claude",
    label: "Claude",
    detail: "Dark · Terracotta",
    appearance: "dark",
    canvas: "#1a1816",
    accent: "#c15f3c",
    category: "dark",
  },
  {
    id: "claude-light",
    label: "Claude Light",
    detail: "Light · Terracotta",
    appearance: "light",
    canvas: "#faf9f5",
    accent: "#c15f3c",
    category: "light",
  },
  {
    id: "codex",
    label: "Codex",
    detail: "Dark · Magenta",
    appearance: "dark",
    canvas: "#101014",
    accent: "#d946ef",
    category: "dark",
  },
  {
    id: "cursor",
    label: "Cursor",
    detail: "Dark · Frost",
    appearance: "dark",
    canvas: "#181818",
    accent: "#88c0d0",
    category: "dark",
  },
  {
    id: "matrix",
    label: "Matrix",
    detail: "Dark · Green",
    appearance: "dark",
    canvas: "#000000",
    accent: "#00e676",
    category: "dark",
  },
];
